Repository huggingface/lighteval, pull requests merged in 2025-09, with the labels that each got.

#956 Multilingual extractiveness
  pyproject.toml
  src/lighteval/metrics/imports/data_stats_metric.py
  src/lighteval/metrics/metrics.py
  src/lighteval/metrics/metrics_sample.py
Labels: feature/enhancement

#963 Added `backend_options` parameter to llm judges.
  src/lighteval/metrics/metrics_sample.py
  src/lighteval/metrics/utils/llm_as_judge.py
Labels: feature/enhancement

#976 Refine acknowledgements in README.md
  README.md
Labels: documentation, ignore-for-release

#951 [RFC] Rework the dependencies to be more versatile
  docs/source/using-the-python-api.mdx
  pyproject.toml
  src/lighteval/logging/evaluation_tracker.py
  src/lighteval/logging/info_loggers.py
  src/lighteval/main_nanotron.py
  src/lighteval/metrics/imports/data_stats_metric.py
  src/lighteval/metrics/normalizations.py
  src/lighteval/metrics/utils/extractive_match_utils.py
  src/lighteval/metrics/utils/linguistic_tokenizers.py
  src/lighteval/metrics/utils/llm_as_judge.py
  src/lighteval/metrics/utils/math_comparison.py
  src/lighteval/models/endpoints/litellm_model.py
  src/lighteval/models/endpoints/tgi_model.py
  src/lighteval/models/model_loader.py
  src/lighteval/models/nanotron/nanotron_model.py
  src/lighteval/models/sglang/sglang_model.py
  src/lighteval/models/transformers/adapter_model.py
  src/lighteval/models/transformers/transformers_model.py
  src/lighteval/models/transformers/vlm_transformers_model.py
  src/lighteval/models/vllm/vllm_model.py
  src/lighteval/pipeline.py
  src/lighteval/tasks/extended/__init__.py
  src/lighteval/tasks/extended/ifbench/instructions.py
  src/lighteval/tasks/extended/ifeval/instructions.py
  src/lighteval/tasks/extended/ifeval/main.py
  src/lighteval/tasks/registry.py
  src/lighteval/utils/imports.py
  src/lighteval/utils/parallelism.py
  tests/test_dependencies.py
  tests/unit/models/test_transformers_model.py
  tests/unit/pipeline/test_reasoning_tags.py
  tests/unit/utils/test_caching.py
  tests/utils.py
Labels: feature/enhancement, refacto
