Repository huggingface/lighteval, pull requests merged in 2025-05, with the labels that each got.

#691 Fix TransformersModel.from_model() method
  src/lighteval/models/transformers/transformers_model.py
Labels: bug

#684 Update split iteration for DynamicBatchingDataset
  src/lighteval/data.py
  src/lighteval/models/endpoints/endpoint_model.py
  src/lighteval/models/endpoints/inference_providers_model.py
  src/lighteval/models/endpoints/openai_model.py
  src/lighteval/models/litellm_model.py
  src/lighteval/models/sglang/sglang_model.py
  src/lighteval/models/transformers/transformers_model.py
  src/lighteval/models/vllm/vllm_model.py
Labels: feature/enhancement

#605 docs: improve consistency in punctuation of metric list
  docs/source/metric-list.mdx
Labels: documentation

#701 [FIX] Inference providers
  pyproject.toml
  src/lighteval/models/endpoints/inference_providers_model.py
Labels: bug, feature/enhancement

#703 Update README.md
  README.md
Labels: documentation, ignore-for-release

#702 Fix typos
  docs/source/adding-a-custom-task.mdx
  docs/source/use-sglang-as-backend.mdx
  docs/source/use-vllm-as-backend.mdx
  src/lighteval/logging/evaluation_tracker.py
  src/lighteval/logging/info_loggers.py
  src/lighteval/main_custom.py
  src/lighteval/metrics/dynamic_metrics.py
  src/lighteval/metrics/metrics.py
  src/lighteval/models/endpoints/tgi_model.py
  src/lighteval/models/nanotron/nanotron_model.py
  src/lighteval/tasks/extended/lcb/codegen_metrics.py
  src/lighteval/tasks/templates/hellaswag.py
Labels: documentation, ignore-for-release

#708 Patch 0.9.1
  docs/source/evaluating-a-custom-model.mdx
  src/lighteval/data.py
  src/lighteval/models/abstract_model.py
  src/lighteval/models/endpoints/inference_providers_model.py
  tests/test_unit_reorder.py
Labels: bug, ignore-for-release

#711 Fix tqdm logging
  src/lighteval/metrics/stderr.py
  src/lighteval/models/transformers/transformers_model.py
Labels: bug, ignore-for-release

#690 Added support for quantization in vLLM backend
  src/lighteval/models/vllm/vllm_model.py
Labels: feature/enhancement

#694 Adds More Generative tasks
  src/lighteval/metrics/dynamic_metrics.py
  src/lighteval/tasks/default_prompts.py
  src/lighteval/tasks/default_tasks.py
Labels: new-task, task-update

#739 Update main_endpoint.py
  src/lighteval/main_endpoint.py
Labels: bug, ignore-for-release

#675 Adds multimodal support and MMMU pro
  examples/model_configs/transformers_vlm_model.yaml
  pyproject.toml
  src/lighteval/main_accelerate.py
  src/lighteval/models/model_loader.py
  src/lighteval/models/transformers/vlm_transformers_model.py
  src/lighteval/tasks/default_prompts.py
  src/lighteval/tasks/default_tasks.py
  src/lighteval/tasks/lighteval_task.py
  src/lighteval/tasks/prompt_manager.py
  src/lighteval/tasks/requests.py
  tests/reference_scores/Qwen2.5-VL-3B-Instruct-results-vlm.json
  tests/reference_scores/Qwen2.5-VL-7B-Instruct-results-vlm.json
  tests/slow_tests/test_accelerate_vlm_model.py
Labels: feature/enhancement

#743 Fix task metric type mismatch
  src/lighteval/tasks/default_tasks.py
Labels: bug, ignore-for-release

#734 Add MCQ support to Yourbench evaluation
  examples/custom_tasks_templates/custom_yourbench_task_mcq.py
  src/lighteval/metrics/utils/extractive_match_utils.py
  tests/metrics/test_extractive_match.py
Labels: task-update

#754 Allow for model kwargs when loading transformers from pretrained
  src/lighteval/models/transformers/transformers_model.py
Labels: feature/enhancement

#755 Adds template for custom path saving results
  docs/source/saving-and-reading-results.mdx
  src/lighteval/config/lighteval_config.py
  src/lighteval/logging/evaluation_tracker.py
  src/lighteval/main_accelerate.py
  src/lighteval/main_custom.py
  src/lighteval/main_endpoint.py
  src/lighteval/main_nanotron.py
  src/lighteval/main_sglang.py
  src/lighteval/main_vllm.py
  tests/logging/test_evaluation_tracker.py
Labels: feature/enhancement

#767 add dependencies to run after pip install
  pyproject.toml
Labels: bug, ignore-for-release

#768 Add missing model_name fixes
  examples/custom_models/local_mt_model.py
  src/lighteval/models/endpoints/openai_model.py
Labels: bug, ignore-for-release

#693 Async vllm
  pyproject.toml
  src/lighteval/models/abstract_model.py
  src/lighteval/models/model_loader.py
  src/lighteval/models/transformers/adapter_model.py
  src/lighteval/models/transformers/delta_model.py
  src/lighteval/models/vllm/vllm_model.py
  src/lighteval/pipeline.py
Labels: feature/enhancement

#777 Bump dev version to 0.10.1.dev0
  pyproject.toml
Labels: ignore-for-release

#697 Making bootstrap_iters an arg
  src/lighteval/logging/info_loggers.py
  src/lighteval/pipeline.py
Labels: feature/enhancement
